name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and release
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: make

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false
          files: |
            trash
          name: ${{ github.ref }}
